export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SEND_FILTER_PARAMS = 'SEND_FILTER_PARAMS';


export const ADD_PRODUCT_TO_COMPARISONS = 'ADD_PRODUCT_TO_COMPARISONS';
export const REMOVE_PRODUCT_FROM_COMPARISONS = 'REMOVE_PRODUCT_FROM_COMPARISONS';
export const REMOVE_ALL_PRODUCTS_FROM_COMPARISONS = 'REMOVE_ALL_PRODUCTS_FROM_COMPARISONS'

export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
export const REMOVE_ALL_PRODUCTS_FROM_WISHLIST = 'REMOVE_ALL_PRODUCTS_FROM_WISHLIST'

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET'
export const REMOVE_ALL_PRODUCTS_FROM_BASKET = 'REMOVE_ALL_PRODUCTS_FROM_BASKET'

