export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SEND_FILTER_PARAMS = 'SEND_FILTER_PARAMS';


export const ADD_COMPARISONS = 'ADD_COMPARISONS';
export const REMOVE_COMPARISONS = 'REMOVE_COMPARISONS';

export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';