export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SEND_FILTER_PARAMS = 'SEND_FILTER_PARAMS';


export const ADD_PRODUCT_TO_COMPARISONS = 'ADD_PRODUCT_TO_COMPARISONS';
export const REMOVE_PRODUCT_FROM_COMPARISONS = 'REMOVE_PRODUCT_FROM_COMPARISONS';
export const REMOVE_ALL_PRODUCTS_FROM_COMPARISONS = 'REMOVE_ALL_PRODUCTS_FROM_COMPARISONS'
export const UPDATE_COMPARE_PRODUCTS = 'UPDATE_COMPARE_PRODUCTS'

export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
export const REMOVE_ALL_PRODUCTS_FROM_WISHLIST = 'REMOVE_ALL_PRODUCTS_FROM_WISHLIST'
export const UPDATE_WISHLIST_PRODUCTS = 'UPDATE_WISHLIST_PRODUCTS'

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET'
export const REMOVE_ALL_PRODUCTS_FROM_BASKET = 'REMOVE_ALL_PRODUCTS_FROM_BASKET'
export const UPDATE_BASKET_PRODUCTS = 'UPDATE_BASKET_PRODUCTS'

export const INCREASE_BASKET_PRODUCT_AMOUNT = 'INCREASE_BASKET_PRODUCT_AMOUNT'
export const DECREASE_BASKET_PRODUCT_AMOUNT = 'DECREASE_BASKET_PRODUCT_AMOUNT'
export const SET_BASKET_PRODUCT_AMOUNT = 'SET_BASKET_PRODUCT_AMOUNT'
export const SEND_BASKET_TOTAL = 'SEND_BASKET_TOTAL'

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'

export const SEND_CATALOG_COLOR = 'SEND_CATALOG_COLOR'
export const SAVE_CATALOG_COLOR = 'SAVE_CATALOG_COLOR'


export const SAVE_USER_DATA = 'SAVE_USER_DATA' 
export const UPDATE_USERS_DATA = 'UPDATE_USERS_DATA'


export const OPEN_ACTIVE_USER_ACCOUNT = 'OPEN_ACTIVE_USER_ACCOUNT'
export const UPDATE_ACTIVE_PROFILE_DATA = 'UPDATE_ACTIVE_PROFILE_DATA'
export const DELETE_ACTIVE_PROFILE = 'DELETE_ACTIVE_PROFILE'
export const LOG_OUT_ACTIVE_PROFILE = 'LOG_OUT_ACTIVE_PROFILE'


export const SEND_ORDER_DATA = 'SEND_ORDER_DATA'
export const DELETE_ORDER_DATA = 'DELETE_ORDER_DATA'